### ISSUE TITLE
working in terminal but not in wm

### ISSUE THREAD

**Issue by newincpp** [nyyManni/dmenu-wayland#1]
Hi,
I just switch from X11 to wayland I was trying to find a remplacement for my dmenu
I tried a bunch but your is the only one that satisfy me except I could make it work in real environment:
I use sway (just like you it seems).
here what I did:
`set $menu dmenu-wl_path | dmenu-wl --height 20 -i  --selected-background "#5322A8" | xargs swaymsg exec`
problem is: it doesn't grab inputs so I just have a bar hanging at the top on my screen doing nothing and the windows where I was continue to catch my inputs.
Can you add on your readme how did you made it work ?

**Comment by nyyManni** [comment]
Which version of Sway are you running? I am currently on Sway 1.0 and have no issues with grabbing of the keyboard focus.

As the application launcher I use the `dmenu-wl_run` -executable (part of this repo), and have it bound to Super+D with:
```
bindsym $mod+d exec dmenu-wl_run -b -i
```

**Comment by newincpp** [comment]
sway --version give me:
`sway version 1.0`
it doesn't work either with the call directly in bindsym instead of setting $menu
just incase here is my sway config file: https://git.psychoscientists.com/newin/usefulFiles/src/master/swayConfig I'm not sure if it's a bug in dmenu or a conflict in the config file yet

**Comment by nyyManni** [comment]
Did you try to use `exec` on `dmenu-wl` directly in the config instead of running it through `swaymsg`? I'm thinking that maybe the focusing is lost there.

Also, try with the exact config line that I shared, so that we can rule out an issue with the config.

**Comment by newincpp** [comment]
`set $menu dmenu-wl_run` in the config file didn't work
`bindsym $mod+d exec dmenu-wl_run` in config file didn't work
`swaymsg exec dmenu-wl_run` from a terminal work
not sure that's happening, the fact it work with swaymsg only in terminal doesn't make any sense to me.

**Comment by nyyManni** [comment]
Sounds really strange indeed. One more thing that comes to my mind is that you seem to be running a multi-monitor setup, and also have two input methods (trackpad and a wacom). Maybe that gets dmenu confused?

I haven't had a chance to test this with a multi-monitor setup yet, so I don't really even expect it to work there yet. Give it a shot with a single monitor only?

**Comment by newincpp** [comment]
unplugging my second monitor made it work indeed !

**Comment by nyyManni** [comment]
Good to know. I have an extra monitor laying around somewhere, so I'll try to come up with a patch in a few days.

**Comment by nyyManni** [comment]
I was able to replicate the issue.

**Comment by nyyManni** [comment]
This should be fixed now. Also the -m/--monitor -option can now be used to select the monitor which dmenu-wl renders on.
