### ISSUE TITLE
Maybe don't set exclusive zone?

### ISSUE THREAD

**Issue by mortie** [nyyManni/dmenu-wayland#15]
The way most launchers (including dmenu with xwayland) works is that they just create an overlay, hiding whatever is behind them, without affecting the size of existing windows. However, since dmenu-wayland uses `zwlr_layer_surface_v1_set_exclusive_zone` to set the exclusive zone to 10px, it moves windows around in a way I consider kind of awkward. Maybe make it an option?

In any case, if you want to keep the exclusive zones (either as an option or not), the size should probably be `10 * panel->monitor->scale` instead of `10`; currently, on my 2x scaled monitor, the exclusive zone is smaller than the size of the window, because the exclusive zone is 10 physical pixels while the window is 10 logical (20 physical) pixels.

**Comment by ids1024** [comment]
Passing `-1` instead of `10` seems to work, and match the behavior of the dmenu.

That should probably at least be an option. Though, I don't personally see why someone would want the menu to temporarily rescale all their open windows.
