### ISSUE TITLE
Unable to pass program arguments

### ISSUE THREAD

**Issue by onny** [nyyManni/dmenu-wayland#2]
Hey,
thanks for this nice program.
It works quite good already but I'm missing the ability to pass command line arguments to the programs.
For example, launching ``firefox`` works fine but ``firefox -p`` doesn't work. The ``-p`` parameter is ignored.

Best regards,
Jonas

**Comment by nyyManni** [comment]
There was indeed a difference to the way dmenu for X handled program arguments. Fixed that.
