### ISSUE TITLE
highpriority patch from suckless dmenu [feature request]

### ISSUE THREAD

**Issue by akawama** [nyyManni/dmenu-wayland#22]
Hello,

I think something like this patch would be really helpful. Would you please consider adding something like this?

_[highpriority](https://tools.suckless.org/dmenu/patches/highpriority/)
"This patch will automatically sort the search result so that high priority items are shown first."_

**Comment by yakthungba** [comment]
It seems editing the .dmenu_cache wroks equally well.

**Comment by nyyManni** [comment]
In my opinion this should be implemented as a separate utility that goes in between dmenu-wl_path and dmenu-wl.

That loses the ability to highlight the highprio items, but gains more flexibility in sorting or filtering the items based on some criteria. It would also be directly compatible with dmenu for X and possibly other similar tools.

**Comment by marendowski** [comment]
Hi! I made a `dmenu-history` shell script which saves the chosen programs to a file in cache and shows them before others (including while searching for something).

It looks like this:
![image](https://github.com/nyyManni/dmenu-wayland/assets/37738748/8c233cfa-277d-4701-9a0e-e7df97b7ae16)

[Link to gist for x11 dmenu](https://gist.github.com/piotr-marendowski/6dcd54bf8ae4fac0b3bb52fa2246daba)
[Link to my `dmenu-wl.sh` in my wayland dotfiles](https://github.com/piotr-marendowski/linux-dotfiles/blob/dwm-wayland/.config/scripts/dmenu-wl.sh)

Hope it helps.
