### ISSUE TITLE
Overlap on waybar

### ISSUE THREAD

**Issue by addy419** [nyyManni/dmenu-wayland#29]
When I start dmenu_wl with `dmenu-wl_run -b -h 32 -i -p "run:"` it overlaps on the normal window instead of waybar. I want to overlap it with waybar, what should I do?

**Comment by marendowski** [comment]
Hi, I have the same issue with [dwlb](https://github.com/kolunmi/dwlb) and [dwl-bar](https://github.com/MadcowOG/dwl-bar), have you found a fix to it?
